// File generated by FlutterFire CLI — regenerate this before your first build.
//
// This checked-in version is a PLACEHOLDER so the project compiles out of
// the box. Run the following locally (or in a Codemagic build step) once
// you've created your Firebase project and added an Android app to it:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure --project=<your-firebase-project-id> --platforms=android
//
// That command overwrites this file with your real Android `appId`,
// `apiKey`, `projectId`, `messagingSenderId`, and `storageBucket`, and also
// drops `google-services.json` into android/app/. Do NOT ship this
// placeholder to production — FCM will silently fail to authenticate.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'dart:io' show Platform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (Platform.isAndroid) return android;
    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for this platform. '
      'TickBell targets Android only — run `flutterfire configure --platforms=android`.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_FIREBASE_ANDROID_API_KEY',
    appId: 'REPLACE_WITH_FIREBASE_ANDROID_APP_ID',
    messagingSenderId: 'REPLACE_WITH_FIREBASE_MESSAGING_SENDER_ID',
    projectId: 'REPLACE_WITH_FIREBASE_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_FIREBASE_PROJECT_ID.appspot.com',
  );
}
